# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('record_input', models.DateTimeField(default=django.utils.timezone.now)),
                ('age', models.FloatField(default=0)),
                ('type', models.CharField(choices=[('cat', 'Cats and Kittens'), ('rabbit_gp', 'Rabbits and Guinea Pigs'), ('small_furries', 'Small furries'), ('other', 'Other')], default='other', max_length=50)),
                ('image', models.ImageField(upload_to='/image_uploads')),
            ],
        ),
    ]
