# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='author',
        ),
    ]
