# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(upload_to='image_uploads'),
        ),
    ]
