# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20161220_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
