# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20161221_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('Cats and Kittens', 'Cats and Kittens'), ('Rabbits and Guinea Pigs', 'Rabbits and Guinea Pigs'), ('Small Furries', 'Small Furries'), ('Other', 'Other')], default='other', max_length=50),
        ),
    ]
