# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20161221_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('record_input', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
