# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_start', models.DateTimeField()),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.RenameField(
            model_name='news',
            old_name='description',
            new_name='body',
        ),
    ]
