# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20161223_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200)),
                ('animal_id', models.FloatField(default=0)),
                ('contact_email', models.EmailField(default='none@none.com', max_length=254)),
                ('contact_text', models.TextField()),
            ],
        ),
    ]
