# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_animalcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalcontact',
            name='animal_id',
            field=models.IntegerField(default=0),
        ),
    ]
